#!/bin/zsh

DIR=`dirname $0`
EXE=`basename $0`
DB=${DIR}/db/playlists.db

cd ${DIR}

zparseopts -D -F -K -- \
   {h,-help}=flag_help \
   {r,-reset}=flag_reset

(

echo "*************** Start ***************" | tee /dev/stderr
date  | tee /dev/stderr


if (( ${flag_reset} )); then
  echo "Doing a full refresh"
  rm -f ${DB}
  rm -f ${DIR}/data/load_state.json 
fi

echo "Fetching playlists"
${DIR}/bin/python ${DIR}/scripts/rpl.py 

echo "Creating schema"
cat ${DIR}/sql/create_schema.sql | sqlite3 ${DB}

echo "Loading playlists"
${DIR}/bin/python ${DIR}/scripts/plloader.py

echo "Load Song Counts"
cat ${DIR}/sql/load_song_counts.sql | sqlite3 ${DB}

echo "Load Stations"
cat ${DIR}/sql/load_stations.sql | sqlite3 ${DB}

echo "Loading Discogs Data"
cat ${DIR}/sql/load_discogs.sql     | sqlite3 ${DB}

echo "Matching artists and titles"
${DIR}/bin/python ${DIR}/scripts/matcha.py

echo "Create Matched Data"
cat ${DIR}/sql/load_matched.sql      | sqlite3 ${DB}

date | tee /dev/stderr
echo "**************** End ****************" | tee /dev/stderr

) 1>>${DIR}/logs/${EXE}.out.log 2>>${DIR}/logs/${EXE}.err.log
